name: qr-mia
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.1
  - torchvision>=0.16
  - numpy>=1.23
  - scikit-learn>=1.3
  - tqdm
  - pyyaml
  - pip
  - pip:
      - pytest>=7.0
