arch: unet_small
data_root: data
dataset: cifar10
diffusion:
  T: 1000
  beta_schedule: linear
  loss: eps_mse
img_size: 32
logging:
  log_interval: 100
  out_dir: runs/ddpm/cifar10
model:
  base_channels: 128
  channel_mults:
  - 1
  - 2
  - 2
  - 4
  dropout: 0.0
  num_res_blocks: 2
train:
  batch_size: 16
  betas:
  - 0.9
  - 0.999
  ema: true
  ema_decay: 0.999
  epochs: 2
  grad_clip: 1.0
  lr: 0.0002
  num_workers: 4
  seed: 0
  weight_decay: 0.0
