seed: 20251030
target_fprs: [0.001, 0.0001]

t_error:
  T: 1000
  k_uniform: 50
  aggregate: mean
  cache_dir: scores

model:
  checkpoint_root: runs/ddim_cifar10/main
  prefer_ema: true
  config: configs/model_ddim.yaml

bagging:
  B: 50
  bootstrap_ratio: 0.8
  tau_values: [0.001, 0.0001]

train:
  epochs: 50
  batch_size: 256
  lr: 0.001
  weight_decay: 0.0
  cosine_anneal: true
  val_ratio: 0.1
  log1p: true
  tau_warmup:
    epochs: 3
    value: 0.005

logging:
  level: INFO
  output_dir: runs/attack_qr
