dataset: cifar10
seed: 0
img_size: 32
public:
  K: 12                    # 每个样本生成 12 个时间步误差对
  mode: eps               # 使用 epsilon 预测模式（与 DDPM 训练一致）
  timesteps: uniform      # 时间步采样方式：均匀分布
  batch_size: 32          # 生成误差对时的批次大小
qr:
  arch: resnet_tiny       # 使用小型 ResNet 作为量化回归模型架构
  opt: adam              # 使用 Adam 优化器
  lr: 1.0e-3            # 学习率 0.001
  epochs: 30            # 训练 30 个 epoch
  batch_size: 256       # 训练批次大小 256
  alpha_list: [0.01, 0.001]  # 正则化参数列表，用于模型选择
bagging:
  M: 16                 # 训练 16 个不同的量化回归模型
  bootstrap: true       # 启用 Bootstrap 采样
