eval:
  alpha: 0.01        # 正则化参数，用于模型选择
  mode: x0          # 评估时使用 x0 重建误差
  K: 4              # 每个样本生成 4 个时间步误差对
  batch_size: 128   # 评估批次大小
  bootstrap: 200    # Bootstrap 采样次数
  seed: 0          # 随机种子
